from .typings import Document


class Updater:
    def __init__(self, input_filename: str, output_filename: str) -> None: ...

    def __enter__(self) -> None: ...

    def __exit__(self, *args): ...

    def update(self, document: Document) -> None: ...
